package com.closehousie.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6750a4)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFeed0f7)
val md_theme_light_onPrimaryContainer = Color(0xFF21005d)
val md_theme_light_secondary = Color(0xFF625b71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe8def8)
val md_theme_light_onSecondaryContainer = Color(0xFF1d192b)
val md_theme_light_tertiary = Color(0xFF7d5260)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd8e4)
val md_theme_light_onTertiaryContainer = Color(0xFF31111d)
val md_theme_light_error = Color(0xFFb3261e)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_errorContainer = Color(0xFFf9dedc)
val md_theme_light_onErrorContainer = Color(0xFF410e0b)
val md_theme_light_background = Color(0xFfffbfe0)
val md_theme_light_onBackground = Color(0xFF1c1b1f)
val md_theme_light_surface = Color(0xFfffbfe0)
val md_theme_light_onSurface = Color(0xFF1c1b1f)
val md_theme_light_outline = Color(0xFF79747e)
val md_theme_light_surfaceVariant = Color(0xFFe7e0ec)
val md_theme_light_onSurfaceVariant = Color(0xFF49454e)

val md_theme_dark_primary = Color(0xFFd0bcff)
val md_theme_dark_onPrimary = Color(0xFF371e55)
val md_theme_dark_primaryContainer = Color(0xFF4f378b)
val md_theme_dark_onPrimaryContainer = Color(0xFFeed0f7)
val md_theme_dark_secondary = Color(0xFFccc7f0)
val md_theme_dark_onSecondary = Color(0xFF332d41)
val md_theme_dark_secondaryContainer = Color(0xFF4a4458)
val md_theme_dark_onSecondaryContainer = Color(0xFFe8def8)
val md_theme_dark_tertiary = Color(0xFFf0b8d0)
val md_theme_dark_onTertiary = Color(0xFF492532)
val md_theme_dark_tertiaryContainer = Color(0xFF633b48)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd8e4)
val md_theme_dark_error = Color(0xFFf2b8b5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8c1d18)
val md_theme_dark_onErrorContainer = Color(0xFFf9dedc)
val md_theme_dark_background = Color(0xFF1c1b1f)
val md_theme_dark_onBackground = Color(0xFFe6e1e6)
val md_theme_dark_surface = Color(0xFF1c1b1f)
val md_theme_dark_onSurface = Color(0xFFe6e1e6)
val md_theme_dark_outline = Color(0xFF9a9798)
val md_theme_dark_surfaceVariant = Color(0xFF49454e)
val md_theme_dark_onSurfaceVariant = Color(0xFFcac7d0)
